name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.0.0"

publish_to: none


dependencies:
  flutter:
    sdk: flutter 
  http:
  meta: 
  csv: ^5.0.0
  recase: 
  code_builder:
  dart_style: ^2.0.0 
  source_gen:
  flutter_sheet_localization: 
    git:
      url: https://github.com/idompolo/flutter_sheet_localization
  build: 
  analyzer: 
  collection: 
  intl:
  localization_builder:

dev_dependencies:
  build_runner: 
